version: '3.8'
services:
  app:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network
  api:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/backend
    networks:
      - app-network
  db:
    image: mongodb:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db
networks:
  app-network:
